### ISSUE TITLE
Server error in subscription.cancel

### ISSUE THREAD

**Issue by cberkom** [chartmogul/chartmogul-ruby#72]
Hi, we've started getting this issue when trying to cancel a subscription, this code work previously:

```ruby
> ChartMogul::Subscription.all(customer_uuid).first
=> #<ChartMogul::Subscription:0x000055ede4b7ebe8
 @cancellation_dates=[],
 @data_source_uuid="ds_redacted-1ae8-46d9-b24d-a8474ebefa21",
 @external_id="sub_custom_fah_b_2688",
 @plan_uuid="pl_redacted-744f-48f4-a384-b557ff203b67",
 @uuid="sub_redacted-6db3-4f97-b34d-669cd6f2d7c2">

> ChartMogul::Subscription.all(customer_uuid).first.cancel(Time.now)
ChartMogul::ServerError: ChartMogul API server response error (HTTP Status: 500)
Response: {"error":"Internal server error"}
from /app/vendor/bundle/ruby/2.5.0/gems/chartmogul-ruby-1.5.1/lib/chartmogul/api_resource.rb:71:in `handle_request_error'
Caused by Faraday::ClientError: the server responded with status 500
from /app/vendor/bundle/ruby/2.5.0/gems/faraday-0.17.3/lib/faraday/response/raise_error.rb:15:in `on_complete'
```

**Comment by pkopac** [comment]
Hi @cberkom,

this is a temporary error type. I recommend adding exponential retry up to N seconds. Since you haven't provided timestamp to match against logs, I have to guess that it matches the event I found - a dependent service not being available temporarily.

If you can reproduce it consistently, that would be a different situation, but I haven't found this to occur frequently in the logs.

**Comment by cberkom** [comment]
I can confirm that the problem is temporary, it worked this morning.
